lib/teacher_web/router.ex
defmodule TeacherWeb.Router do
  use TeacherWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TeacherWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TeacherWeb do
    pipe_through :browser

    resources "/albums", AlbumController, except: [:index]
    live "/albums", AlbumLive.Index, :index
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", TeacherWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TeacherWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/teacher/recordings/album.ex
defmodule Teacher.Recordings.Album do
  use Ecto.Schema
  import Ecto.Changeset

  schema "albums" do
    field :artist, :string
    field :summary, :string
    field :title, :string
    field :year, :integer

    timestamps()
  end

  @doc false
  def changeset(album, attrs) do
    album
    |> cast(attrs, [:artist, :summary, :title, :year])
    |> validate_required([:artist, :summary, :title, :year])
  end
end

lib/teacher_web/controllers/album_controller.ex
defmodule TeacherWeb.AlbumController do
  use TeacherWeb, :controller

  alias Teacher.Recordings
  alias Teacher.Recordings.Album

  def new(conn, _params) do
    changeset = Recordings.change_album(%Album{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"album" => album_params}) do
    case Recordings.create_album(album_params) do
      {:ok, album} ->
        conn
        |> put_flash(:info, "Album created successfully.")
        |> redirect(to: Routes.album_path(conn, :show, album))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    album = Recordings.get_album!(id)
    render(conn, "show.html", album: album)
  end

  def edit(conn, %{"id" => id}) do
    album = Recordings.get_album!(id)
    changeset = Recordings.change_album(album)
    render(conn, "edit.html", album: album, changeset: changeset)
  end

  def update(conn, %{"id" => id, "album" => album_params}) do
    album = Recordings.get_album!(id)

    case Recordings.update_album(album, album_params) do
      {:ok, album} ->
        conn
        |> put_flash(:info, "Album updated successfully.")
        |> redirect(to: Routes.album_path(conn, :show, album))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", album: album, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    album = Recordings.get_album!(id)
    {:ok, _album} = Recordings.delete_album(album)

    conn
    |> put_flash(:info, "Album deleted successfully.")
    |> redirect(to: Routes.album_path(conn, :index))
  end
end

lib/teacher_web/views/album_view.ex
defmodule TeacherWeb.AlbumView do
  use TeacherWeb, :view
end

lib/teacher_web/templates/album/edit.html.heex
<h1>Edit Album</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.album_path(@conn, :update, @album)) %>

<span><%= link "Back", to: Routes.album_index_path(@conn, :index) %></span>

lib/teacher_web/templates/album/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :artist %>
  <%= text_input f, :artist %>
  <%= error_tag f, :artist %>

  <%= label f, :summary %>
  <%= text_input f, :summary %>
  <%= error_tag f, :summary %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :year %>
  <%= number_input f, :year %>
  <%= error_tag f, :year %>

  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/teacher_web/templates/album/new.html.heex
<h1>New Album</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.album_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.album_path(@conn, :index) %></span>

lib/teacher_web/templates/album/show.html.heex
<h1>Show Album</h1>

<ul>

  <li>
    <strong>Artist:</strong>
    <%= @album.artist %>
  </li>

  <li>
    <strong>Summary:</strong>
    <%= @album.summary %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @album.title %>
  </li>

  <li>
    <strong>Year:</strong>
    <%= @album.year %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.album_path(@conn, :edit, @album) %></span> |
<span><%= link "Back", to: Routes.album_index_path(@conn, :index) %></span>